"""empty message

Revision ID: 06a10b3160b1
Revises: 12afbbd1b96a
Create Date: 2017-11-27 23:00:34.111381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a10b3160b1'
down_revision = '12afbbd1b96a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commentaries', sa.Column('is_journal', sa.Boolean()))
    #op.drop_column('commentaries', 'title')
    #op.create_foreign_key(None, 'tags', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.add_column('commentaries', sa.Column('title', sa.TEXT(), nullable=True))
    op.drop_column('commentaries', 'is_journal')
    # ### end Alembic commands ###
