"""empty message

Revision ID: 12afbbd1b96a
Revises: 1253a34c52fb
Create Date: 2017-10-25 22:59:09.831313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12afbbd1b96a'
down_revision = '1253a34c52fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('default_tag', sa.Text(), nullable=True))
    #op.drop_column('commentaries', 'title')
    #op.create_foreign_key(None, 'tags', 'users', ['user_id'], ['id'])
    op.add_column('user_actions', sa.Column('tag', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_actions', 'tag')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.add_column('commentaries', sa.Column('title', sa.TEXT(), nullable=True))
    op.drop_column('actions', 'default_tag')
    # ### end Alembic commands ###
