"""empty message

Revision ID: 2f5abd277f57
Revises: 21d6a9f40991
Create Date: 2017-07-16 22:47:47.460172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f5abd277f57'
down_revision = '21d6a9f40991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('actions', sa.Column('creator_user_id', sa.Integer(), nullable=True))
    op.add_column('actions', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('actions', sa.Column('initial_nb_days', sa.Integer(), nullable=True))
    op.add_column('actions', sa.Column('is_personal_action', sa.Boolean(), nullable=True))
    op.add_column('actions', sa.Column('public', sa.Boolean(), nullable=True))
    op.add_column('actions', sa.Column('start_date', sa.DateTime(), nullable=True))
    #op.create_foreign_key(None, 'actions', 'users', ['creator_user_id'], ['id'])
    #op.drop_column('actions', 'value')
    op.add_column('ressources', sa.Column('url', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('points_env', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('points_pers', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('points_rel', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'points_rel')
    op.drop_column('users', 'points_pers')
    op.drop_column('users', 'points_env')
    op.drop_column('ressources', 'url')
    op.add_column('actions', sa.Column('value', sa.VARCHAR(length=7), nullable=False))
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.drop_column('actions', 'start_date')
    op.drop_column('actions', 'public')
    op.drop_column('actions', 'is_personal_action')
    op.drop_column('actions', 'initial_nb_days')
    op.drop_column('actions', 'end_date')
    op.drop_column('actions', 'creator_user_id')
    op.drop_column('actions', 'created_at')
    # ### end Alembic commands ###
