"""empty message

Revision ID: 3aabc5b8e32b
Revises: 2f5abd277f57
Create Date: 2017-08-29 22:39:40.759344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aabc5b8e32b'
down_revision = '2f5abd277f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('kind', sa.Text(), nullable=False))
    op.alter_column('actions', 'creator_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'actions', 'users', ['creator_user_id'], ['id'])
    op.drop_column('actions', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('value', sa.VARCHAR(length=7), nullable=False))
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.alter_column('actions', 'creator_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('actions', 'kind')
    # ### end Alembic commands ###
