"""empty message

Revision ID: 7f2256e64779
Revises: c31f38f66b40
Create Date: 2018-05-04 16:17:09.492663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f2256e64779'
down_revision = 'c31f38f66b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_like')
    op.add_column('actions', sa.Column('like', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('actions', 'nb_like')
    op.add_column('users', sa.Column('connexions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'connexions')
    op.add_column('actions', sa.Column('nb_like', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('actions', 'like')
    op.create_table('action_like',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name='action_like_action_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='action_like_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'action_id', name='action_like_pkey')
    )
    # ### end Alembic commands ###
