"""empty message

Revision ID: ab4f76ad43a0
Revises: 9aded47717e6
Create Date: 2017-10-20 14:40:59.611617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4f76ad43a0'
down_revision = '9aded47717e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('is_event', sa.Boolean(), nullable=True))
    #op.drop_column('commentaries', 'title')
    op.add_column('users', sa.Column('has_image', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_image')
    op.add_column('commentaries', sa.Column('title', sa.TEXT(), nullable=True))
    op.drop_column('actions', 'is_event')
    # ### end Alembic commands ###
