"""empty message

Revision ID: bd1852c4906a
Revises: ab4f76ad43a0
Create Date: 2017-10-20 14:52:01.082927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1852c4906a'
down_revision = 'ab4f76ad43a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    #op.drop_column('commentaries', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commentaries', sa.Column('title', sa.TEXT(), nullable=True))
    op.drop_table('tags')
    # ### end Alembic commands ###
