"""empty message

Revision ID: f1e3f538a5ea
Revises: 7f2256e64779
Create Date: 2018-05-04 17:28:42.317260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1e3f538a5ea'
down_revision = '7f2256e64779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('user_likes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('actions', 'like')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('like', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('actions', 'user_likes')
    # ### end Alembic commands ###
